/*
 * This code was ported from scipy using c2rust, followed by a manual cleanup.
 * These files where used:
 * - cephes/scipy_iv.c -> iv.rs
 * - cephes/polevl.h -> polynomials.rs
 * - cephes/j0.c -> j0.rs
 * - cephes/j1.c -> j1.rs
 * - cephes/{jv.c, yn.c, yv.c} -> jv.rs
 * - cephes/airy.c -> airy.rs
 *
 *
 * Parts of the code are copyright:
 *
 *     Cephes Math Library Release 2.8:  June, 2000
 *     Copyright 1984, 1987, 1988, 2000 by Stephen L. Moshier
 *
 * And other parts:
 *
 *     Copyright (c) 2006 Xiaogang Zhang
 *     Use, modification and distribution are subject to the
 *     Boost Software License, Version 1.0.
 *
 *     Boost Software License - Version 1.0 - August 17th, 2003
 *
 *     Permission is hereby granted, free of charge, to any person or
 *     organization obtaining a copy of the software and accompanying
 *     documentation covered by this license (the "Software") to use, reproduce,
 *     display, distribute, execute, and transmit the Software, and to prepare
 *     derivative works of the Software, and to permit third-parties to whom the
 *     Software is furnished to do so, all subject to the following:
 *
 *     The copyright notices in the Software and this entire statement,
 *     including the above license grant, this restriction and the following
 *     disclaimer, must be included in all copies of the Software, in whole or
 *     in part, and all derivative works of the Software, unless such copies or
 *     derivative works are solely in the form of machine-executable object code
 *     generated by a source language processor.
 *
 *     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 *     OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *     MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
 *     NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
 *     DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
 *     WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 *     CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *     SOFTWARE.
 *
 * And the rest are:
 *
 *     Copyright (C) 2009 Pauli Virtanen
 *     Distributed under the same license as Scipy.
 *
 */

#![allow(dead_code)]

const MAXLOG: f64 = 7.09782712893384e2;     /* f64::ln(f64::MAX) */

mod polynomials;
pub use self::polynomials::{eval_polynomial, eval_polynomial_1};

mod airy;
pub use self::airy::airy;

mod iv;
pub use self::iv::bessel_iv;

mod j0;
pub use self::j0::{bessel_j0, bessel_y0};

mod j1;
pub use self::j1::{bessel_j1, bessel_y1};

mod jv;
pub use self::jv::{bessel_jv, bessel_yn, bessel_yv};
pub use self::jv::{spherical_bessel_jv, spherical_bessel_yv};
