@PACKAGE_INIT@

if(rascaline_FOUND)
    return()
endif()

add_library(rascaline SHARED IMPORTED GLOBAL)
set_target_properties(rascaline PROPERTIES
    IMPORTED_LOCATION ${PACKAGE_PREFIX_DIR}/@LIB_INSTALL_DIR@/@RASCALINE_LIB_NAME@
    INTERFACE_INCLUDE_DIRECTORIES ${PACKAGE_PREFIX_DIR}/@INCLUDE_INSTALL_DIR@/
)
